services:
  - type: web
    name: flixverse-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: streaming-web-2272d
      - key: CORS_ORIGINS
        value: https://flixverse-streaming-pro.vercel.app,http://localhost:3000
